/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnu.gmp.swig;

public class gmp {
  public static long mpz_alloc_init() {
    return gmpJNI.mpz_alloc_init();
  }

  public static void mpz_clear_free(long arg0) {
    gmpJNI.mpz_clear_free(arg0);
  }

  public static long mpq_alloc_init() {
    return gmpJNI.mpq_alloc_init();
  }

  public static void mpq_clear_free(long arg0) {
    gmpJNI.mpq_clear_free(arg0);
  }

  public static long mpf_alloc_init() {
    return gmpJNI.mpf_alloc_init();
  }

  public static void mpf_clear_free(long arg0) {
    gmpJNI.mpf_clear_free(arg0);
  }

  public static void mpz_abs(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_abs(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpz_add(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_add(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_add_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_add_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_addmul(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_addmul(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_addmul_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_addmul_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_and(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_and(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_array_init(SWIGTYPE_p_mpz_ptr arg0, long arg1, long arg2) {
    gmpJNI.mpz_array_init(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpz_bin_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_bin_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_bin_uiui(SWIGTYPE_p_mpz_ptr arg0, long arg1, long arg2) {
    gmpJNI.mpz_bin_uiui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpz_cdiv_q(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_cdiv_q(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_cdiv_q_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_cdiv_q_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_cdiv_qr(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, SWIGTYPE_p_mpz_ptr arg3) {
    gmpJNI.mpz_cdiv_qr(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), SWIGTYPE_p_mpz_ptr.getCPtr(arg3));
  }

  public static long mpz_cdiv_qr_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, long arg3) {
    return gmpJNI.mpz_cdiv_qr_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), arg3);
  }

  public static void mpz_cdiv_r(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_cdiv_r(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_cdiv_r_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_cdiv_r_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static long mpz_cdiv_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return gmpJNI.mpz_cdiv_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_clear(SWIGTYPE_p_mpz_ptr arg0) {
    gmpJNI.mpz_clear(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static int mpz_cmp(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_cmp(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static int mpz_cmp_d(SWIGTYPE_p_mpz_ptr arg0, double arg1) {
    return gmpJNI.mpz_cmp_d(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int _mpz_cmp_si(SWIGTYPE_p_mpz_ptr arg0, int arg1) {
    return gmpJNI._mpz_cmp_si(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int _mpz_cmp_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return gmpJNI._mpz_cmp_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int mpz_cmpabs(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_cmpabs(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static int mpz_cmpabs_d(SWIGTYPE_p_mpz_ptr arg0, double arg1) {
    return gmpJNI.mpz_cmpabs_d(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int mpz_cmpabs_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return gmpJNI.mpz_cmpabs_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_com(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_com(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static int mpz_congruent_p(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    return gmpJNI.mpz_congruent_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static int mpz_congruent_ui_p(SWIGTYPE_p_mpz_ptr arg0, long arg1, long arg2) {
    return gmpJNI.mpz_congruent_ui_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpz_divexact(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_divexact(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_divexact_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_divexact_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static int mpz_divisible_p(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_divisible_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static int mpz_divisible_ui_p(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return gmpJNI.mpz_divisible_ui_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_dump(SWIGTYPE_p_mpz_ptr arg0) {
    gmpJNI.mpz_dump(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static SWIGTYPE_p_void mpz_export(SWIGTYPE_p_void arg0, SWIGTYPE_p_unsigned_long arg1, int arg2, long arg3, int arg4, long arg5, SWIGTYPE_p_mpz_ptr arg6) {
    long cPtr = gmpJNI.mpz_export(SWIGTYPE_p_void.getCPtr(arg0), SWIGTYPE_p_unsigned_long.getCPtr(arg1), arg2, arg3, arg4, arg5, SWIGTYPE_p_mpz_ptr.getCPtr(arg6));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void mpz_fac_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    gmpJNI.mpz_fac_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_fdiv_q(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_fdiv_q(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_fdiv_q_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_fdiv_q_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_fdiv_qr(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, SWIGTYPE_p_mpz_ptr arg3) {
    gmpJNI.mpz_fdiv_qr(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), SWIGTYPE_p_mpz_ptr.getCPtr(arg3));
  }

  public static long mpz_fdiv_qr_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, long arg3) {
    return gmpJNI.mpz_fdiv_qr_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), arg3);
  }

  public static void mpz_fdiv_r(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_fdiv_r(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_fdiv_r_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_fdiv_r_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static long mpz_fdiv_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return gmpJNI.mpz_fdiv_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_fib_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    gmpJNI.mpz_fib_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_fib2_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_fib2_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static int mpz_fits_sint_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_fits_sint_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static int mpz_fits_slong_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_fits_slong_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static int mpz_fits_sshort_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_fits_sshort_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static int mpz_fits_uint_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_fits_uint_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static int mpz_fits_ulong_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_fits_ulong_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static int mpz_fits_ushort_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_fits_ushort_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static void mpz_gcd(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_gcd(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_gcd_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_gcd_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_gcdext(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, SWIGTYPE_p_mpz_ptr arg3, SWIGTYPE_p_mpz_ptr arg4) {
    gmpJNI.mpz_gcdext(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), SWIGTYPE_p_mpz_ptr.getCPtr(arg3), SWIGTYPE_p_mpz_ptr.getCPtr(arg4));
  }

  public static double mpz_get_d(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_get_d(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static double mpz_get_d_2exp(SWIGTYPE_p_long arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_get_d_2exp(SWIGTYPE_p_long.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static int mpz_get_si(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_get_si(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static String mpz_get_str(String arg0, int arg1, SWIGTYPE_p_mpz_ptr arg2) {
    return gmpJNI.mpz_get_str(arg0, arg1, SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_get_ui(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_get_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static SWIGTYPE_p_mp_limb_t mpz_getlimbn(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return new SWIGTYPE_p_mp_limb_t(gmpJNI.mpz_getlimbn(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1), true);
  }

  public static void mpz_import(SWIGTYPE_p_mpz_ptr arg0, long arg1, int arg2, long arg3, int arg4, long arg5, SWIGTYPE_p_void arg6) {
    gmpJNI.mpz_import(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, arg2, arg3, arg4, arg5, SWIGTYPE_p_void.getCPtr(arg6));
  }

  public static void mpz_init(SWIGTYPE_p_mpz_ptr arg0) {
    gmpJNI.mpz_init(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static void mpz_init_set(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_init_set(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpz_init_set_d(SWIGTYPE_p_mpz_ptr arg0, double arg1) {
    gmpJNI.mpz_init_set_d(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_init_set_si(SWIGTYPE_p_mpz_ptr arg0, int arg1) {
    gmpJNI.mpz_init_set_si(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int mpz_init_set_str(SWIGTYPE_p_mpz_ptr arg0, String arg1, int arg2) {
    return gmpJNI.mpz_init_set_str(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpz_init_set_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    gmpJNI.mpz_init_set_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static long mpz_inp_raw(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_FILE arg1) {
    return gmpJNI.mpz_inp_raw(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_FILE.getCPtr(arg1));
  }

  public static long mpz_inp_str(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_FILE arg1, int arg2) {
    return gmpJNI.mpz_inp_str(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_FILE.getCPtr(arg1), arg2);
  }

  public static int mpz_invert(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    return gmpJNI.mpz_invert(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_ior(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_ior(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static int mpz_jacobi(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_jacobi(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static int mpz_kronecker_si(SWIGTYPE_p_mpz_ptr arg0, int arg1) {
    return gmpJNI.mpz_kronecker_si(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int mpz_kronecker_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return gmpJNI.mpz_kronecker_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int mpz_si_kronecker(int arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_si_kronecker(arg0, SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static int mpz_ui_kronecker(long arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_ui_kronecker(arg0, SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpz_lcm(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_lcm(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_lcm_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_lcm_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_lucnum_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    gmpJNI.mpz_lucnum_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_lucnum2_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_lucnum2_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static int mpz_millerrabin(SWIGTYPE_p_mpz_ptr arg0, int arg1) {
    return gmpJNI.mpz_millerrabin(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_mod(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_mod(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_mul(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_mul(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_mul_si(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, int arg2) {
    gmpJNI.mpz_mul_si(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_mul_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_mul_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_neg(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_neg(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpz_nextprime(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_nextprime(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static long mpz_out_raw(SWIGTYPE_p_FILE arg0, SWIGTYPE_p_mpz_ptr arg1) {
    return gmpJNI.mpz_out_raw(SWIGTYPE_p_FILE.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static long mpz_out_str(SWIGTYPE_p_FILE arg0, int arg1, SWIGTYPE_p_mpz_ptr arg2) {
    return gmpJNI.mpz_out_str(SWIGTYPE_p_FILE.getCPtr(arg0), arg1, SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static int mpz_perfect_power_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_perfect_power_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static int mpz_perfect_square_p(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_perfect_square_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static void mpz_pow_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_pow_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_powm(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, SWIGTYPE_p_mpz_ptr arg3) {
    gmpJNI.mpz_powm(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), SWIGTYPE_p_mpz_ptr.getCPtr(arg3));
  }

  public static void mpz_powm_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2, SWIGTYPE_p_mpz_ptr arg3) {
    gmpJNI.mpz_powm_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2, SWIGTYPE_p_mpz_ptr.getCPtr(arg3));
  }

  public static int mpz_probab_prime_p(SWIGTYPE_p_mpz_ptr arg0, int arg1) {
    return gmpJNI.mpz_probab_prime_p(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_random(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    gmpJNI.mpz_random(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_random2(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    gmpJNI.mpz_random2(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int mpz_root(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_root(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_rootrem(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, long arg3) {
    gmpJNI.mpz_rootrem(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), arg3);
  }

  public static void mpz_set(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_set(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpz_set_d(SWIGTYPE_p_mpz_ptr arg0, double arg1) {
    gmpJNI.mpz_set_d(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_set_f(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpz_set_f(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpz_set_q(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpz_set_q(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpz_set_si(SWIGTYPE_p_mpz_ptr arg0, int arg1) {
    gmpJNI.mpz_set_si(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static int mpz_set_str(SWIGTYPE_p_mpz_ptr arg0, String arg1, int arg2) {
    return gmpJNI.mpz_set_str(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpz_set_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    gmpJNI.mpz_set_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static long mpz_size(SWIGTYPE_p_mpz_ptr arg0) {
    return gmpJNI.mpz_size(SWIGTYPE_p_mpz_ptr.getCPtr(arg0));
  }

  public static long mpz_sizeinbase(SWIGTYPE_p_mpz_ptr arg0, int arg1) {
    return gmpJNI.mpz_sizeinbase(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_sqrt(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_sqrt(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpz_sqrtrem(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_sqrtrem(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_sub(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_sub(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_sub_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_sub_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_ui_sub(SWIGTYPE_p_mpz_ptr arg0, long arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_ui_sub(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_submul(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_submul(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpz_submul_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    gmpJNI.mpz_submul_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_swap(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpz_swap(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static long mpz_tdiv_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1) {
    return gmpJNI.mpz_tdiv_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1);
  }

  public static void mpz_tdiv_q(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_tdiv_q(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_tdiv_q_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_tdiv_q_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_tdiv_qr(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, SWIGTYPE_p_mpz_ptr arg3) {
    gmpJNI.mpz_tdiv_qr(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), SWIGTYPE_p_mpz_ptr.getCPtr(arg3));
  }

  public static long mpz_tdiv_qr_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2, long arg3) {
    return gmpJNI.mpz_tdiv_qr_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2), arg3);
  }

  public static void mpz_tdiv_r(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_tdiv_r(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static long mpz_tdiv_r_ui(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, long arg2) {
    return gmpJNI.mpz_tdiv_r_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), arg2);
  }

  public static void mpz_ui_pow_ui(SWIGTYPE_p_mpz_ptr arg0, long arg1, long arg2) {
    gmpJNI.mpz_ui_pow_ui(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpz_xor(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpz_ptr arg1, SWIGTYPE_p_mpz_ptr arg2) {
    gmpJNI.mpz_xor(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1), SWIGTYPE_p_mpz_ptr.getCPtr(arg2));
  }

  public static void mpq_abs(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpq_abs(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpq_add(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1, SWIGTYPE_p_mpq_ptr arg2) {
    gmpJNI.mpq_add(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1), SWIGTYPE_p_mpq_ptr.getCPtr(arg2));
  }

  public static void mpq_canonicalize(SWIGTYPE_p_mpq_ptr arg0) {
    gmpJNI.mpq_canonicalize(SWIGTYPE_p_mpq_ptr.getCPtr(arg0));
  }

  public static void mpq_clear(SWIGTYPE_p_mpq_ptr arg0) {
    gmpJNI.mpq_clear(SWIGTYPE_p_mpq_ptr.getCPtr(arg0));
  }

  public static int mpq_cmp(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    return gmpJNI.mpq_cmp(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static int _mpq_cmp_si(SWIGTYPE_p_mpq_ptr arg0, int arg1, long arg2) {
    return gmpJNI._mpq_cmp_si(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static int _mpq_cmp_ui(SWIGTYPE_p_mpq_ptr arg0, long arg1, long arg2) {
    return gmpJNI._mpq_cmp_ui(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpq_div(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1, SWIGTYPE_p_mpq_ptr arg2) {
    gmpJNI.mpq_div(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1), SWIGTYPE_p_mpq_ptr.getCPtr(arg2));
  }

  public static int mpq_equal(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    return gmpJNI.mpq_equal(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpq_get_num(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpq_get_num(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpq_get_den(SWIGTYPE_p_mpz_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpq_get_den(SWIGTYPE_p_mpz_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static double mpq_get_d(SWIGTYPE_p_mpq_ptr arg0) {
    return gmpJNI.mpq_get_d(SWIGTYPE_p_mpq_ptr.getCPtr(arg0));
  }

  public static String mpq_get_str(String arg0, int arg1, SWIGTYPE_p_mpq_ptr arg2) {
    return gmpJNI.mpq_get_str(arg0, arg1, SWIGTYPE_p_mpq_ptr.getCPtr(arg2));
  }

  public static void mpq_init(SWIGTYPE_p_mpq_ptr arg0) {
    gmpJNI.mpq_init(SWIGTYPE_p_mpq_ptr.getCPtr(arg0));
  }

  public static long mpq_inp_str(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_FILE arg1, int arg2) {
    return gmpJNI.mpq_inp_str(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_FILE.getCPtr(arg1), arg2);
  }

  public static void mpq_inv(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpq_inv(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpq_mul(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1, SWIGTYPE_p_mpq_ptr arg2) {
    gmpJNI.mpq_mul(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1), SWIGTYPE_p_mpq_ptr.getCPtr(arg2));
  }

  public static void mpq_neg(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpq_neg(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static long mpq_out_str(SWIGTYPE_p_FILE arg0, int arg1, SWIGTYPE_p_mpq_ptr arg2) {
    return gmpJNI.mpq_out_str(SWIGTYPE_p_FILE.getCPtr(arg0), arg1, SWIGTYPE_p_mpq_ptr.getCPtr(arg2));
  }

  public static void mpq_set(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpq_set(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpq_set_d(SWIGTYPE_p_mpq_ptr arg0, double arg1) {
    gmpJNI.mpq_set_d(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), arg1);
  }

  public static void mpq_set_den(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpq_set_den(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpq_set_f(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpq_set_f(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpq_set_num(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpq_set_num(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpq_set_si(SWIGTYPE_p_mpq_ptr arg0, int arg1, long arg2) {
    gmpJNI.mpq_set_si(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static int mpq_set_str(SWIGTYPE_p_mpq_ptr arg0, String arg1, int arg2) {
    return gmpJNI.mpq_set_str(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpq_set_ui(SWIGTYPE_p_mpq_ptr arg0, long arg1, long arg2) {
    gmpJNI.mpq_set_ui(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpq_set_z(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpq_set_z(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static void mpq_sub(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1, SWIGTYPE_p_mpq_ptr arg2) {
    gmpJNI.mpq_sub(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1), SWIGTYPE_p_mpq_ptr.getCPtr(arg2));
  }

  public static void mpq_swap(SWIGTYPE_p_mpq_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpq_swap(SWIGTYPE_p_mpq_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpf_abs(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_abs(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpf_add(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, SWIGTYPE_p_mpf_ptr arg2) {
    gmpJNI.mpf_add(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), SWIGTYPE_p_mpf_ptr.getCPtr(arg2));
  }

  public static void mpf_add_ui(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, long arg2) {
    gmpJNI.mpf_add_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), arg2);
  }

  public static void mpf_ceil(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_ceil(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpf_clear(SWIGTYPE_p_mpf_ptr arg0) {
    gmpJNI.mpf_clear(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static int mpf_cmp(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    return gmpJNI.mpf_cmp(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static int mpf_cmp_d(SWIGTYPE_p_mpf_ptr arg0, double arg1) {
    return gmpJNI.mpf_cmp_d(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static int mpf_cmp_si(SWIGTYPE_p_mpf_ptr arg0, int arg1) {
    return gmpJNI.mpf_cmp_si(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static int mpf_cmp_ui(SWIGTYPE_p_mpf_ptr arg0, long arg1) {
    return gmpJNI.mpf_cmp_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static void mpf_div(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, SWIGTYPE_p_mpf_ptr arg2) {
    gmpJNI.mpf_div(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), SWIGTYPE_p_mpf_ptr.getCPtr(arg2));
  }

  public static void mpf_div_ui(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, long arg2) {
    gmpJNI.mpf_div_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), arg2);
  }

  public static void mpf_dump(SWIGTYPE_p_mpf_ptr arg0) {
    gmpJNI.mpf_dump(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static int mpf_fits_sint_p(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_fits_sint_p(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static int mpf_fits_slong_p(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_fits_slong_p(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static int mpf_fits_sshort_p(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_fits_sshort_p(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static int mpf_fits_uint_p(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_fits_uint_p(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static int mpf_fits_ulong_p(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_fits_ulong_p(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static int mpf_fits_ushort_p(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_fits_ushort_p(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static void mpf_floor(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_floor(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static double mpf_get_d(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_get_d(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static double mpf_get_d_2exp(SWIGTYPE_p_long arg0, SWIGTYPE_p_mpf_ptr arg1) {
    return gmpJNI.mpf_get_d_2exp(SWIGTYPE_p_long.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static int mpf_get_si(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_get_si(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static String mpf_get_str(String arg0, SWIGTYPE_p_mp_exp_t arg1, int arg2, long arg3, SWIGTYPE_p_mpf_ptr arg4) {
    return gmpJNI.mpf_get_str(arg0, SWIGTYPE_p_mp_exp_t.getCPtr(arg1), arg2, arg3, SWIGTYPE_p_mpf_ptr.getCPtr(arg4));
  }

  public static long mpf_get_ui(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_get_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static void mpf_init(SWIGTYPE_p_mpf_ptr arg0) {
    gmpJNI.mpf_init(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static void mpf_init_set(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_init_set(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpf_init_set_d(SWIGTYPE_p_mpf_ptr arg0, double arg1) {
    gmpJNI.mpf_init_set_d(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static void mpf_init_set_si(SWIGTYPE_p_mpf_ptr arg0, int arg1) {
    gmpJNI.mpf_init_set_si(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static int mpf_init_set_str(SWIGTYPE_p_mpf_ptr arg0, String arg1, int arg2) {
    return gmpJNI.mpf_init_set_str(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpf_init_set_ui(SWIGTYPE_p_mpf_ptr arg0, long arg1) {
    gmpJNI.mpf_init_set_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static long mpf_inp_str(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_FILE arg1, int arg2) {
    return gmpJNI.mpf_inp_str(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_FILE.getCPtr(arg1), arg2);
  }

  public static int mpf_integer_p(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_integer_p(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static void mpf_mul(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, SWIGTYPE_p_mpf_ptr arg2) {
    gmpJNI.mpf_mul(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), SWIGTYPE_p_mpf_ptr.getCPtr(arg2));
  }

  public static void mpf_mul_ui(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, long arg2) {
    gmpJNI.mpf_mul_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), arg2);
  }

  public static void mpf_neg(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_neg(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static long mpf_out_str(SWIGTYPE_p_FILE arg0, int arg1, long arg2, SWIGTYPE_p_mpf_ptr arg3) {
    return gmpJNI.mpf_out_str(SWIGTYPE_p_FILE.getCPtr(arg0), arg1, arg2, SWIGTYPE_p_mpf_ptr.getCPtr(arg3));
  }

  public static void mpf_pow_ui(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, long arg2) {
    gmpJNI.mpf_pow_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), arg2);
  }

  public static void mpf_random2(SWIGTYPE_p_mpf_ptr arg0, long arg1, SWIGTYPE_p_mp_exp_t arg2) {
    gmpJNI.mpf_random2(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1, SWIGTYPE_p_mp_exp_t.getCPtr(arg2));
  }

  public static void mpf_reldiff(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, SWIGTYPE_p_mpf_ptr arg2) {
    gmpJNI.mpf_reldiff(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), SWIGTYPE_p_mpf_ptr.getCPtr(arg2));
  }

  public static void mpf_set(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_set(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpf_set_d(SWIGTYPE_p_mpf_ptr arg0, double arg1) {
    gmpJNI.mpf_set_d(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static void mpf_set_q(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpq_ptr arg1) {
    gmpJNI.mpf_set_q(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpq_ptr.getCPtr(arg1));
  }

  public static void mpf_set_si(SWIGTYPE_p_mpf_ptr arg0, int arg1) {
    gmpJNI.mpf_set_si(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static int mpf_set_str(SWIGTYPE_p_mpf_ptr arg0, String arg1, int arg2) {
    return gmpJNI.mpf_set_str(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1, arg2);
  }

  public static void mpf_set_ui(SWIGTYPE_p_mpf_ptr arg0, long arg1) {
    gmpJNI.mpf_set_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static void mpf_set_z(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpz_ptr arg1) {
    gmpJNI.mpf_set_z(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpz_ptr.getCPtr(arg1));
  }

  public static long mpf_size(SWIGTYPE_p_mpf_ptr arg0) {
    return gmpJNI.mpf_size(SWIGTYPE_p_mpf_ptr.getCPtr(arg0));
  }

  public static void mpf_sqrt(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_sqrt(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpf_sqrt_ui(SWIGTYPE_p_mpf_ptr arg0, long arg1) {
    gmpJNI.mpf_sqrt_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1);
  }

  public static void mpf_sub(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, SWIGTYPE_p_mpf_ptr arg2) {
    gmpJNI.mpf_sub(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), SWIGTYPE_p_mpf_ptr.getCPtr(arg2));
  }

  public static void mpf_sub_ui(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1, long arg2) {
    gmpJNI.mpf_sub_ui(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1), arg2);
  }

  public static void mpf_swap(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_swap(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpf_trunc(SWIGTYPE_p_mpf_ptr arg0, SWIGTYPE_p_mpf_ptr arg1) {
    gmpJNI.mpf_trunc(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), SWIGTYPE_p_mpf_ptr.getCPtr(arg1));
  }

  public static void mpf_ui_div(SWIGTYPE_p_mpf_ptr arg0, long arg1, SWIGTYPE_p_mpf_ptr arg2) {
    gmpJNI.mpf_ui_div(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1, SWIGTYPE_p_mpf_ptr.getCPtr(arg2));
  }

  public static void mpf_ui_sub(SWIGTYPE_p_mpf_ptr arg0, long arg1, SWIGTYPE_p_mpf_ptr arg2) {
    gmpJNI.mpf_ui_sub(SWIGTYPE_p_mpf_ptr.getCPtr(arg0), arg1, SWIGTYPE_p_mpf_ptr.getCPtr(arg2));
  }

}
